/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust test suite for a Web File System API
 *    (FileSystemHandle) glob matching library. This involved validating
 *    standard glob syntax (wildcards, globstars, braces, extglobs, character
 *    classes) using Vitest with mocked directory handles, stress-testing
 *    performance for large brace expansions through regex-based segment
 *    matching, and verifying the reliability of options such as maxDepth,
 *    ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */
import * as fs from 'node:fs'
import * as path from 'node:path'
import { BaseFileSystemDirectoryHandle, BaseFileSystemFileHandle } from '../setup'

export class MockFileSystemFileHandle extends BaseFileSystemFileHandle {
  constructor(name: string) {
    super(name)
  }
}

export class MockFileSystemDirectoryHandle extends BaseFileSystemDirectoryHandle {
  private _fsPath: string

  constructor(name: string, fsPath: string) {
    super(name)
    this._fsPath = fsPath
  }

  override async *values(): AsyncIterableIterator<
    MockFileSystemFileHandle | MockFileSystemDirectoryHandle
  > {
    const entries = fs.readdirSync(this._fsPath, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(this._fsPath, entry.name)
      if (entry.isDirectory()) {
        yield new MockFileSystemDirectoryHandle(entry.name, fullPath)
      } else if (entry.isFile()) {
        yield new MockFileSystemFileHandle(entry.name)
      }
    }
  }

  override async getDirectoryHandle(
    name: string,
  ): Promise<MockFileSystemDirectoryHandle> {
    const fullPath = path.join(this._fsPath, name)
    try {
      const stat = fs.statSync(fullPath)
      if (stat.isDirectory()) {
        return new MockFileSystemDirectoryHandle(name, fullPath)
      }
    } catch {}
    throw new DOMException('Not found', 'NotFoundError')
  }

  override async getFileHandle(name: string): Promise<MockFileSystemFileHandle> {
    const fullPath = path.join(this._fsPath, name)
    try {
      const stat = fs.statSync(fullPath)
      if (stat.isFile()) {
        return new MockFileSystemFileHandle(name)
      }
    } catch {}
    throw new DOMException('Not found', 'NotFoundError')
  }
}

export function createMockDirectoryHandle(
  rootPath: string,
): MockFileSystemDirectoryHandle {
  const resolved = path.resolve(rootPath)
  const name = path.basename(resolved)
  return new MockFileSystemDirectoryHandle(name, resolved)
}

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
