/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust test suite for a Web File System API
 *    (FileSystemHandle) glob matching library. This involved validating
 *    standard glob syntax (wildcards, globstars, braces, extglobs, character
 *    classes) using Vitest with mocked directory handles, stress-testing
 *    performance for large brace expansions through regex-based segment
 *    matching, and verifying the reliability of options such as maxDepth,
 *    ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */
import { GlobOptions, glob as nodeGlob } from 'glob'
import { expect, it } from 'vitest'
import { GlobRunner } from '../src/services/GlobRunner'
import { GlobOptions as WebFsGlobOptions } from '../src/types'
import { FIXTURE_ROOT } from './fixtures/setup'
import { createMockDirectoryHandle } from './mocks/MockFileSystemHandle'

export type Opts = Partial<Omit<WebFsGlobOptions, 'cwd'>>

export interface TestCase {
  name: string
  pattern: string
  options?: Opts
}

export async function runWebFsGlob(
  pattern: string,
  options: Opts = {},
): Promise<string[]> {
  const mockHandle = createMockDirectoryHandle(FIXTURE_ROOT)
  const runner = new GlobRunner({ cwd: mockHandle as any, ...options })
  const results = await runner.run(pattern)
  return results
    .map((r) => r.path)
    .filter((r) => !r.startsWith('casing/'))
    .sort()
}

export async function runGlob(
  pattern: string,
  options: Opts = {},
): Promise<string[]> {
  const fgOptions: GlobOptions = {
    cwd: FIXTURE_ROOT,
    dot: options.dot ?? false,
    maxDepth: options.maxDepth ?? Infinity,
    ignore: options.ignore ?? [],
    nodir: options.nodir ?? false,
    matchBase: options.matchBase ?? false,
    withFileTypes: false,
  }

  const results = (await nodeGlob(pattern, fgOptions)) as string[]
  return results
    .map((r) => r.replaceAll('\\', '/'))
    .filter((r) => !r.startsWith('casing/'))
    .sort()
}

export function runTestCases(cases: TestCase[]) {
  for (const tc of cases) {
    it(tc.name, async () => {
      const webFsResults = await runWebFsGlob(tc.pattern, tc.options)
      const globResults = await runGlob(tc.pattern, tc.options)

      const onlyInWebFs = webFsResults.filter((p) => !globResults.includes(p))
      const onlyInGlob = globResults.filter((p) => !webFsResults.includes(p))

      if (onlyInWebFs.length > 0 || onlyInGlob.length > 0) {
        console.log(`\n⎯⎯⎯⎯⎯⎯⎯ パターン: ${tc.pattern} ⎯⎯⎯⎯⎯⎯⎯`)
        if (onlyInWebFs.length > 0) {
          console.log('web-fs-glob にだけ存在:', onlyInWebFs)
        }
        if (onlyInGlob.length > 0) {
          console.log('glob にだけ存在:', onlyInGlob)
        }
      }

      expect(webFsResults).toEqual(globResults)
    })
  }
}

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
