/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust glob matching library for the Web File
 *    System API (FileSystemHandle). This included implementing standard glob
 *    syntax (wildcards, globstars, braces, extglobs, character classes),
 *    creating a comprehensive test suite using Vitest with mocked directory
 *    handles, optimizing performance for large brace expansions using
 *    regex-based segment matching, and ensuring correct behavior for options
 *    like maxDepth, ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */
/**
 * GlobOptions のテストじゃ。
 * 各オプションが正しく動作するか、本家 glob ライブラリと比較するぞ。
 *
 * 対象オプション:
 *   dot, ignore, matchBase, maxDepth, nodir, signal
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { GlobRunner } from '../src/services/GlobRunner'
import { FIXTURE_ROOT, createFixtures, removeFixtures } from './fixtures/setup'
import { TestCase, runTestCases } from './helpers'
import { createMockDirectoryHandle } from './mocks/MockFileSystemHandle'

// ────────────────────────────────────────
// セットアップ
// ────────────────────────────────────────

beforeAll(() => createFixtures())
afterAll(() => removeFixtures())

// ────────────────────────────────────────
// テストケース定義
// ────────────────────────────────────────

// ========================================
//  dot オプション
// ========================================

const dotTests: TestCase[] = [
  // dot: true — 隠しファイルにもマッチする
  {
    name: 'dot=true: ルート直下',
    pattern: 'dotfiles/*',
    options: { dot: true },
  },
  {
    name: 'dot=true: 全体を再帰的に',
    pattern: 'dotfiles/**',
    options: { dot: true },
  },
  {
    name: 'dot=true: .txt ファイル',
    pattern: 'dotfiles/**/*.txt',
    options: { dot: true },
  },
  {
    name: 'dot=true: .json ファイル',
    pattern: 'dotfiles/**/*.json',
    options: { dot: true },
  },
  {
    name: 'dot=true: .yml ファイル',
    pattern: 'dotfiles/**/*.yml',
    options: { dot: true },
  },
  {
    name: 'dot=true: mixed 配下',
    pattern: 'dotfiles/mixed/**',
    options: { dot: true },
  },
  {
    name: 'dot=true: ルート直下の全エントリ',
    pattern: '*',
    options: { dot: true },
  },

  // dot: false（デフォルト）— 隠しファイルが除外される
  {
    name: 'dot=false: ルート直下',
    pattern: 'dotfiles/*',
    options: { dot: false },
  },
  {
    name: 'dot=false: 全体を再帰的に',
    pattern: 'dotfiles/**',
    options: { dot: false },
  },
  {
    name: 'dot=false: mixed 配下',
    pattern: 'dotfiles/mixed/**',
    options: { dot: false },
  },
  {
    name: 'dot=false: ルート直下の全エントリ',
    pattern: '*',
    options: { dot: false },
  },

  // dot + 他オプション複合
  {
    name: 'dot=true + nodir',
    pattern: 'dotfiles/**',
    options: { dot: true, nodir: true },
  },
  {
    name: 'dot=true + nodir: ルート直下',
    pattern: '*',
    options: { dot: true, nodir: true },
  },
]

// ========================================
//  ignore オプション
// ========================================

const ignoreTests: TestCase[] = [
  {
    name: '特定のディレクトリを除外 (utils)',
    pattern: 'ignore/src/**/*.ts',
    options: { ignore: ['**/utils/**'] },
  },
  {
    name: '特定のファイル名を除外 (index.ts)',
    pattern: 'multi/**/*.ts',
    options: { ignore: ['**/index.ts'] },
  },
  {
    name: '複数パターンで除外',
    pattern: 'ignore/**',
    options: { ignore: ['**/dist/**', '**/node_modules/**'] },
  },
  {
    name: 'テストファイルを除外',
    pattern: 'ignore/src/**/*.ts',
    options: { ignore: ['**/*.test.ts', '**/*.spec.ts'] },
  },
  {
    name: '拡張子で除外 (.js)',
    pattern: 'ignore/**',
    options: { ignore: ['**/*.js'] },
  },
  {
    name: '深いパスの除外',
    pattern: 'ignore/**',
    options: { ignore: ['**/deep/**'] },
  },
  {
    name: '複数ディレクトリの除外',
    pattern: 'ignore/**',
    options: { ignore: ['**/components/**', '**/services/**'] },
  },
  {
    name: '__tests__ ディレクトリの除外',
    pattern: 'ignore/**',
    options: { ignore: ['**/__tests__/**'] },
  },
  {
    name: 'ignore + nodir',
    pattern: 'ignore/**',
    options: { ignore: ['**/dist/**'], nodir: true },
  },
  {
    name: 'ignore + globstar で .json 除外',
    pattern: '**',
    options: { ignore: ['**/*.json'] },
  },
]

// ========================================
//  matchBase オプション
// ========================================

const matchBaseTests: TestCase[] = [
  {
    name: 'matchBase: *.tsx（全階層から検索）',
    pattern: '*.tsx',
    options: { matchBase: true },
  },
  {
    name: 'matchBase: *.css',
    pattern: '*.css',
    options: { matchBase: true },
  },
  {
    name: 'matchBase: *.json',
    pattern: '*.json',
    options: { matchBase: true },
  },
  {
    name: 'matchBase: data.js',
    pattern: 'data.js',
    options: { matchBase: true },
  },
  {
    name: 'matchBase: *.txt',
    pattern: '*.txt',
    options: { matchBase: true },
  },
  {
    name: 'matchBase + nodir: *.ts',
    pattern: '*.ts',
    options: { matchBase: true, nodir: true },
  },
  {
    name: 'matchBase + ignore',
    pattern: '*.ts',
    options: { matchBase: true, ignore: ['**/massive/**'] },
  },
]

// ========================================
//  maxDepth オプション
// ========================================

const maxDepthTests: TestCase[] = [
  {
    name: 'maxDepth=1: deep/**',
    pattern: 'deep/**',
    options: { maxDepth: 1 },
  },
  {
    name: 'maxDepth=2: deep/**',
    pattern: 'deep/**',
    options: { maxDepth: 2 },
  },
  {
    name: 'maxDepth=3: deep/**',
    pattern: 'deep/**',
    options: { maxDepth: 3 },
  },
  {
    name: 'maxDepth=5: deep/**',
    pattern: 'deep/**',
    options: { maxDepth: 5 },
  },
  {
    name: 'maxDepth=10: deep/**',
    pattern: 'deep/**',
    options: { maxDepth: 10 },
  },
  {
    name: 'maxDepth=1: multi/**',
    pattern: 'multi/**',
    options: { maxDepth: 1 },
  },
  {
    name: 'maxDepth=2: multi/**',
    pattern: 'multi/**',
    options: { maxDepth: 2 },
  },
  {
    name: 'maxDepth=3: multi/**',
    pattern: 'multi/**',
    options: { maxDepth: 3 },
  },
  {
    name: 'maxDepth=1: **/*.ts',
    pattern: '**/*.ts',
    options: { maxDepth: 1 },
  },
  {
    name: 'maxDepth=2: **/*.ts',
    pattern: '**/*.ts',
    options: { maxDepth: 2 },
  },
  {
    name: 'maxDepth=3: **/*.ts',
    pattern: '**/*.ts',
    options: { maxDepth: 3 },
  },
  {
    name: 'maxDepth=2: deep/**/ (ディレクトリのみ)',
    pattern: 'deep/**/',
    options: { maxDepth: 2 },
  },
  {
    name: 'maxDepth=3: deep/**/ (ディレクトリのみ)',
    pattern: 'deep/**/',
    options: { maxDepth: 3 },
  },
  {
    name: 'maxDepth=2 + nodir',
    pattern: 'multi/**',
    options: { maxDepth: 2, nodir: true },
  },
  {
    name: 'maxDepth=3 + nodir',
    pattern: 'deep/**',
    options: { maxDepth: 3, nodir: true },
  },
]

// ========================================
//  nodir オプション
// ========================================

const nodirTests: TestCase[] = [
  {
    name: 'nodir: basic 配下',
    pattern: 'basic/**',
    options: { nodir: true },
  },
  {
    name: 'nodir: multi 配下',
    pattern: 'multi/**',
    options: { nodir: true },
  },
  {
    name: 'nodir: deep 配下',
    pattern: 'deep/**',
    options: { nodir: true },
  },
  {
    name: 'nodir: trailing 配下',
    pattern: 'trailing/**',
    options: { nodir: true },
  },
  {
    name: 'nodir: ルート直下',
    pattern: '*',
    options: { nodir: true },
  },
  {
    name: 'nodir: 全体',
    pattern: '**',
    options: { nodir: true },
  },
  {
    name: 'nodir: massive 配下',
    pattern: 'massive/**',
    options: { nodir: true },
  },
  {
    name: 'nodir: dirs 配下（空ディレクトリ含む）',
    pattern: 'dirs/**',
    options: { nodir: true },
  },
  {
    name: 'nodir + 末尾スラッシュ（矛盾→空結果）',
    pattern: 'basic/*/',
    options: { nodir: true },
  },
]

// ========================================
//  複合オプション
// ========================================

const combinedTests: TestCase[] = [
  {
    name: 'nodir + ignore',
    pattern: 'ignore/**',
    options: { nodir: true, ignore: ['**/__tests__/**'] },
  },
  {
    name: 'dot + ignore',
    pattern: 'dotfiles/**',
    options: { dot: true, ignore: ['**/.github/**'] },
  },
  {
    name: 'dot + nodir',
    pattern: 'dotfiles/**',
    options: { dot: true, nodir: true },
  },
  {
    name: 'maxDepth + nodir',
    pattern: '**',
    options: { maxDepth: 3, nodir: true },
  },
  {
    name: 'maxDepth + ignore',
    pattern: 'deep/**',
    options: { maxDepth: 5, ignore: ['**/branch-*/**'] },
  },
  {
    name: 'ignore + matchBase',
    pattern: '*.ts',
    options: { matchBase: true, ignore: ['**/massive/**', '**/multi/**'] },
  },
  {
    name: 'nodir + ignore + maxDepth',
    pattern: '**',
    options: { nodir: true, ignore: ['**/massive/**'], maxDepth: 4 },
  },
  {
    name: 'dot + maxDepth',
    pattern: 'dotfiles/**',
    options: { dot: true, maxDepth: 2 },
  },
]

// ────────────────────────────────────────
// describe ブロック
// ────────────────────────────────────────

describe('オプションテスト: dot', () => runTestCases(dotTests))
describe('オプションテスト: ignore', () => runTestCases(ignoreTests))
describe('オプションテスト: matchBase', () => runTestCases(matchBaseTests))
describe('オプションテスト: maxDepth', () => runTestCases(maxDepthTests))
describe('オプションテスト: nodir', () => runTestCases(nodirTests))
describe('オプションテスト: 複合', () => runTestCases(combinedTests))

// ========================================
//  独自テスト (期待値の比較ではなく、例外の発生等を見る)
// ========================================

describe('オプションテスト: signal', () => {
  it('AbortSignal で検索がキャンセルされる', async () => {
    const controller = new AbortController()
    // 即座に abort する
    controller.abort()

    const mockHandle = createMockDirectoryHandle(FIXTURE_ROOT)
    const runner = new GlobRunner({
      cwd: mockHandle as any,
      signal: controller.signal,
    })

    await expect(async () => await runner.run('**')).rejects.toThrow()
  })

  it('timeout 付きの AbortSignal でキャンセルされる', async () => {
    // 10ms のタイムアウトで AbortSignal を作る
    const signal = AbortSignal.timeout(10)

    const mockHandle = createMockDirectoryHandle(FIXTURE_ROOT)

    // 値を返す際に少し待つように prototype ごとモックを上書き
    const originalValues = mockHandle.constructor.prototype.values
    mockHandle.constructor.prototype.values = async function* (this: any) {
      const iterator = originalValues.bind(this)()
      for await (const val of iterator) {
        await new Promise((r) => setTimeout(r, 20))
        yield val
      }
    }

    try {
      const runner = new GlobRunner({
        cwd: mockHandle as any,
        signal,
      })

      // massive 配下は大量のファイルがあるので、処理中にタイムアウトするはず
      await expect(async () => await runner.run('massive/**')).rejects.toThrow()
    } finally {
      // 後始末
      mockHandle.constructor.prototype.values = originalValues
    }
  })
})

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
