/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust test suite for a Web File System API
 *    (FileSystemHandle) glob matching library. This involved validating
 *    standard glob syntax (wildcards, globstars, braces, extglobs, character
 *    classes) using Vitest with mocked directory handles, stress-testing
 *    performance for large brace expansions through regex-based segment
 *    matching, and verifying the reliability of options such as maxDepth,
 *    ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */

export class BaseFileSystemFileHandle {
  readonly kind = 'file'
  readonly name: string

  constructor(name: string = '') {
    this.name = name
  }
}

export class BaseFileSystemDirectoryHandle {
  readonly kind = 'directory'
  readonly name: string

  constructor(name: string = '') {
    this.name = name
  }

  async *values(): AsyncIterableIterator<any> {}

  async getDirectoryHandle(_name: string): Promise<any> {
    throw new DOMException('Not found', 'NotFoundError')
  }

  async getFileHandle(_name: string): Promise<any> {
    throw new DOMException('Not found', 'NotFoundError')
  }
}

;(globalThis as any).FileSystemFileHandle = BaseFileSystemFileHandle
;(globalThis as any).FileSystemDirectoryHandle = BaseFileSystemDirectoryHandle

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
