/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust test suite for a Web File System API
 *    (FileSystemHandle) glob matching library. This involved validating
 *    standard glob syntax (wildcards, globstars, braces, extglobs, character
 *    classes) using Vitest with mocked directory handles, stress-testing
 *    performance for large brace expansions through regex-based segment
 *    matching, and verifying the reliability of options such as maxDepth,
 *    ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */
/**
 * グロブ構文のテストじゃ。
 * フィクスチャを自動生成し、本家 glob ライブラリと結果を比較するぞ。
 *
 * 対象構文:
 *   *, ?, **, [abc], [a-c], [^a-c], [!a-c],
 *   !(…), ?(…), +(…), *(…), @(…),
 *   [[:alpha:]], 末尾スラッシュ, ブレース展開, エスケープ
 */
import { afterAll, beforeAll, describe } from 'vitest'
import { createFixtures, removeFixtures } from './fixtures/setup'
import { TestCase, runTestCases } from './helpers'

// ────────────────────────────────────────
// セットアップ
// ────────────────────────────────────────

beforeAll(() => createFixtures())
afterAll(() => removeFixtures())

// ────────────────────────────────────────
// テストケース定義
// ────────────────────────────────────────

// ========================================
//  1. シングルアスタリスク (*)
// ========================================

const starTests: TestCase[] = [
  { name: 'ルート直下の全エントリ', pattern: '*' },
  { name: 'ルート直下の .txt ファイル', pattern: '*.txt' },
  { name: 'ルート直下の .js ファイル', pattern: '*.js' },
  { name: 'ルート直下の .json ファイル', pattern: '*.json' },
  { name: 'basic/ 直下の全エントリ', pattern: 'basic/*' },
  { name: 'basic/ 直下の .ts ファイル', pattern: 'basic/*.ts' },
  { name: 'basic/ 直下の .txt ファイル', pattern: 'basic/*.txt' },
  { name: 'classes/ 直下の全エントリ', pattern: 'classes/*' },
  { name: 'classes/ 直下の .txt ファイル', pattern: 'classes/*.txt' },
  { name: 'classes/ 直下の .js ファイル', pattern: 'classes/*.js' },
  { name: 'extglobs/ 直下の .ts ファイル', pattern: 'extglobs/*.ts' },
  { name: 'extglobs/ 直下の .js ファイル', pattern: 'extglobs/*.js' },
  { name: 'massive/ 直下の .txt ファイル', pattern: 'massive/*.txt' },
  { name: 'massive/ 直下の .js ファイル', pattern: 'massive/*.js' },
  { name: 'massive/ 直下の .ts ファイル', pattern: 'massive/*.ts' },
]

// ========================================
//  2. シングル文字マッチ (?)
// ========================================

const questionTests: TestCase[] = [
  { name: '1文字ファイル名.txt', pattern: 'basic/?.txt' },
  { name: '1文字ファイル名.js', pattern: 'basic/?.js' },
  { name: '1文字ファイル名.ts', pattern: 'basic/?.ts' },
  { name: '2文字ファイル名.txt', pattern: 'basic/??.txt' },
  { name: '2文字ファイル名.js', pattern: 'basic/??.js' },
  { name: '3文字ファイル名全拡張子', pattern: 'basic/???.*' },
  { name: '4文字ファイル名.ts', pattern: 'basic/????.ts' },
  { name: '5文字ファイル名.ts', pattern: 'basic/?????.ts' },
  { name: 'classes 1文字.txt', pattern: 'classes/?.txt' },
  { name: 'classes 1文字.js', pattern: 'classes/?.js' },
  { name: 'item の後に1文字 (massive)', pattern: 'braces/item?.txt' },
]

// ========================================
//  3. グロブスター (**)
// ========================================

const globstarTests: TestCase[] = [
  { name: 'basic 配下の全 .ts ファイル', pattern: 'basic/**/*.ts' },
  { name: 'basic 配下の全 .js ファイル', pattern: 'basic/**/*.js' },
  { name: 'basic 配下の全エントリ', pattern: 'basic/**' },
  { name: 'classes 配下の全 .txt ファイル', pattern: 'classes/**/*.txt' },
  { name: 'deep 配下の全 file.txt', pattern: 'deep/**/file.txt' },
  { name: 'deep 配下の全 data.js', pattern: 'deep/**/data.js' },
  { name: 'deep 配下の全エントリ', pattern: 'deep/**' },
  { name: 'multi 配下の全 index.ts', pattern: 'multi/**/index.ts' },
  { name: 'multi 配下の全 utils.ts', pattern: 'multi/**/utils.ts' },
  { name: 'multi 配下の全エントリ', pattern: 'multi/**' },
  { name: 'extglobs 配下の全 .test.ts', pattern: 'extglobs/**/*.test.ts' },
  { name: 'ignore 配下の全 .ts ファイル', pattern: 'ignore/**/*.ts' },
  { name: 'trailing 配下の全エントリ', pattern: 'trailing/**' },
  { name: 'massive 配下の全エントリ', pattern: 'massive/**' },
  { name: '全体の全 .json ファイル', pattern: '**/*.json' },
  { name: '全体の全 index.ts', pattern: '**/index.ts' },
]

// ========================================
//  4. 文字クラス [abc] [a-z]
// ========================================

const charClassTests: TestCase[] = [
  { name: '[abc].txt', pattern: 'classes/[abc].txt' },
  { name: '[x-z].txt', pattern: 'classes/[x-z].txt' },
  { name: '[A-Z].txt', pattern: 'classes/[A-Z].txt' },
  { name: '[0-9].txt', pattern: 'classes/[0-9].txt' },
  { name: '[a-f].txt (範囲の一部)', pattern: 'classes/[a-f].txt' },
  { name: '[m-z].txt (後半範囲)', pattern: 'classes/[m-z].txt' },
  { name: '[A-M].txt (大文字前半)', pattern: 'classes/[A-M].txt' },
  { name: '[jt]s 拡張子 (tsとjs)', pattern: 'classes/*.[jt]s' },
  { name: '大文字始まりの .ts ファイル', pattern: 'classes/[A-Z]*.ts' },
  { name: '小文字始まりの .js ファイル', pattern: 'classes/[a-z]*.js' },
]

// ========================================
//  5. 否定文字クラス [^...] [!...]
// ========================================

const negCharClassTests: TestCase[] = [
  { name: '[^abc].txt (a,b,c以外)', pattern: 'classes/[^abc].txt' },
  { name: '[!abc].txt (a,b,c以外)', pattern: 'classes/[!abc].txt' },
  { name: '[^a-m].txt (前半以外)', pattern: 'classes/[^a-m].txt' },
  { name: '[!0-9].txt (数字以外)', pattern: 'classes/[!0-9].txt' },
  { name: '[^A-Z].txt (大文字以外)', pattern: 'classes/[^A-Z].txt' },
  { name: '[!a-z].txt (小文字以外)', pattern: 'classes/[!a-z].txt' },
]

// ========================================
//  6. 拡張グロブ @(...)
// ========================================

const atExtglobTests: TestCase[] = [
  { name: '@(foo|bar).ts', pattern: 'extglobs/@(foo|bar).ts' },
  { name: '@(foo|bar|baz).js', pattern: 'extglobs/@(foo|bar|baz).js' },
  { name: '@(qux|quux).ts', pattern: 'extglobs/@(qux|quux).ts' },
  { name: '@(test|file).txt', pattern: 'extglobs/@(test|file).txt' },
  {
    name: 'nested 内 @(foo|bar).ts',
    pattern: 'extglobs/nested/@(foo|bar).ts',
  },
]

// ========================================
//  7. 拡張グロブ !(...)
// ========================================

const negExtglobTests: TestCase[] = [
  { name: '!(baz).ts (baz以外)', pattern: 'extglobs/!(baz).ts' },
  { name: '!(foo|bar).js', pattern: 'extglobs/!(foo|bar).js' },
  { name: '!(qux).ts', pattern: 'extglobs/!(qux).ts' },
  { name: '*.!(js) (.js以外の拡張子)', pattern: 'extglobs/*.!(js)' },
  { name: '!(*.test).ts (testファイル以外)', pattern: 'extglobs/!(*.test).ts' },
]

// ========================================
//  8. 拡張グロブ ?(...)
// ========================================

const optionalExtglobTests: TestCase[] = [
  { name: '?(pre)test.txt', pattern: 'extglobs/?(pre)test.txt' },
  { name: '?(pre)file.txt', pattern: 'extglobs/?(pre)file.txt' },
  { name: 'foo.?(test.)ts', pattern: 'extglobs/foo.?(test.)ts' },
]

// ========================================
//  9. 拡張グロブ +(...)
// ========================================

const plusExtglobTests: TestCase[] = [
  { name: '+(ab).ts (1回以上)', pattern: 'extglobs/+(ab).ts' },
  { name: '+(xy).js (1回以上)', pattern: 'extglobs/+(xy).js' },
]

// ========================================
// 10. 拡張グロブ *(...)
// ========================================

const starExtglobTests: TestCase[] = [
  { name: '*(xy).js (0回以上)', pattern: 'extglobs/*(xy).js' },
  { name: '*(ab).ts (0回以上)', pattern: 'extglobs/*(ab).ts' },
]

// ========================================
// 11. POSIX文字クラス [[:alpha:]] [[:digit:]]
// ========================================

const posixClassTests: TestCase[] = [
  { name: '[[:alpha:]].txt (英字1文字)', pattern: 'classes/[[:alpha:]].txt' },
  { name: '[[:digit:]].txt (数字1文字)', pattern: 'classes/[[:digit:]].txt' },
  { name: '[[:upper:]].txt (大文字1文字)', pattern: 'classes/[[:upper:]].txt' },
  { name: '[[:lower:]].txt (小文字1文字)', pattern: 'classes/[[:lower:]].txt' },
  {
    name: '[[:alnum:]]*.txt (英数始まり)',
    pattern: 'classes/[[:alnum:]]*.txt',
  },
]

// ========================================
// 12. 末尾スラッシュ (ディレクトリのみ)
// ========================================

const trailingSlashTests: TestCase[] = [
  { name: 'trailing 直下のディレクトリ', pattern: 'trailing/*/' },
  { name: 'trailing 配下の全ディレクトリ', pattern: 'trailing/**/' },
  { name: 'basic 直下のディレクトリ', pattern: 'basic/*/' },
  { name: 'deep 配下の全ディレクトリ', pattern: 'deep/**/' },
  { name: 'multi 配下の全ディレクトリ', pattern: 'multi/**/' },
  { name: 'classes 直下のディレクトリ', pattern: 'classes/*/' },
  { name: 'dotfiles 配下の全ディレクトリ', pattern: 'dotfiles/**/' },
  { name: 'ルート直下のディレクトリ', pattern: '*/' },
]

// ========================================
// 13. ブレース展開 {a,b} {1..5}
// ========================================

const braceTests: TestCase[] = [
  { name: '{foo,bar}.ts', pattern: 'braces/{foo,bar}.ts' },
  { name: '{foo,bar,baz}.js', pattern: 'braces/{foo,bar,baz}.js' },
  { name: '{a,b}/file.ts', pattern: 'braces/{a,b}/file.ts' },
  { name: '{a,b,c}/file.{ts,js}', pattern: 'braces/{a,b,c}/file.{ts,js}' },
  { name: 'item{1..5}.txt (数値範囲)', pattern: 'braces/item{1..5}.txt' },
  {
    name: 'item{1..10}.txt (全範囲)',
    pattern: 'braces/item{1..10}.txt',
  },
  {
    name: '{foo,bar}.{ts,js} (直積)',
    pattern: 'braces/{foo,bar}.{ts,js}',
  },
]

// ========================================
// 14. エスケープ (リテラル記号)
// ========================================

const escapeTests: TestCase[] = [
  {
    name: '\\[test\\].txt (角括弧エスケープ)',
    pattern: 'symbols/\\[test\\].txt',
  },
  {
    name: '\\[abc\\].js (角括弧エスケープ)',
    pattern: 'symbols/\\[abc\\].js',
  },
  {
    name: '\\{braces\\}.js (中括弧エスケープ)',
    pattern: 'symbols/\\{braces\\}.js',
  },
]

// ========================================
// 15. 完全一致 (ワイルドカードなし)
// ========================================

const exactMatchTests: TestCase[] = [
  { name: '存在するファイル', pattern: 'basic/a.txt' },
  { name: '存在するネストファイル', pattern: 'basic/sub/foo.ts' },
  { name: '深いパス', pattern: 'deep/d1/d2/d3/file.txt' },
  { name: '存在しないファイル', pattern: 'basic/nonexistent.txt' },
  { name: '存在しないディレクトリ配下', pattern: 'nonexistent/foo.ts' },
  { name: 'ディレクトリ自体', pattern: 'basic/sub' },
  { name: 'ルート直下のファイル', pattern: 'a.txt' },
  { name: 'LICENSE (拡張子なし)', pattern: 'LICENSE' },
]

// ========================================
// 16. 多段ワイルドカード (** なし)
// ========================================

const multiStarTests: TestCase[] = [
  { name: 'multi/*/*', pattern: 'multi/*/*' },
  { name: 'multi/*/*.ts', pattern: 'multi/*/*.ts' },
  { name: 'multi/*/*/*', pattern: 'multi/*/*/*' },
  { name: 'ignore/src/*/*.ts', pattern: 'ignore/src/*/*.ts' },
  { name: 'deep/*/file.txt', pattern: 'deep/*/file.txt' },
  { name: 'trailing/*/*', pattern: 'trailing/*/*' },
]

// ========================================
// 17. エッジケース
// ========================================

const edgeCaseTests: TestCase[] = [
  { name: '空結果になるパターン', pattern: '**/*.xyz' },
  { name: '空結果の存在しないディレクトリ', pattern: 'nonexistent/**' },
  {
    name: '同名ファイルが複数階層にある',
    pattern: 'multi/**/index.ts',
  },
  {
    name: '同名ディレクトリが複数にある',
    pattern: 'multi/**/x/',
  },
  {
    name: '深いパスの完全一致',
    pattern: 'deep/d1/d2/d3/d4/d5/d6/d7/d8/d9/d10/file.txt',
  },
  {
    name: '@ フォルダパス',
    pattern: 'symbols/*',
  },
  {
    name: '空ディレクトリを含む検索',
    pattern: 'dirs/**',
  },
  {
    name: '空ディレクトリのみ (末尾/)',
    pattern: 'dirs/**/',
  },
]

// ────────────────────────────────────────
// describe ブロック
// ────────────────────────────────────────

describe('構文テスト: シングルアスタリスク (*)', () => runTestCases(starTests))
describe('構文テスト: シングル文字マッチ (?)', () => runTestCases(questionTests))
describe('構文テスト: グロブスター (**)', () => runTestCases(globstarTests))
describe('構文テスト: 文字クラス [abc] [a-z]', () => runTestCases(charClassTests))
describe('構文テスト: 否定文字クラス [^...] [!...]', () =>
  runTestCases(negCharClassTests))
describe('構文テスト: 拡張グロブ @(...)', () => runTestCases(atExtglobTests))
describe('構文テスト: 拡張グロブ !(...)', () => runTestCases(negExtglobTests))
describe('構文テスト: 拡張グロブ ?(...)', () => runTestCases(optionalExtglobTests))
describe('構文テスト: 拡張グロブ +(...)', () => runTestCases(plusExtglobTests))
describe('構文テスト: 拡張グロブ *(...)', () => runTestCases(starExtglobTests))
describe('構文テスト: POSIX文字クラス', () => runTestCases(posixClassTests))
describe('構文テスト: 末尾スラッシュ', () => runTestCases(trailingSlashTests))
describe('構文テスト: ブレース展開 {a,b}', () => runTestCases(braceTests))
describe('構文テスト: エスケープ', () => runTestCases(escapeTests))
describe('構文テスト: 完全一致', () => runTestCases(exactMatchTests))
describe('構文テスト: 多段ワイルドカード', () => runTestCases(multiStarTests))
describe('構文テスト: エッジケース', () => runTestCases(edgeCaseTests))

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
