/*!
 * ============================================================================
 *                             AI Generation Notice
 * ============================================================================
 *  Generated by Gemini 3 Flash, an AI developed by Google DeepMind.
 *  Source Prompt: Developing a robust test suite for a Web File System API
 *    (FileSystemHandle) glob matching library. This involved validating
 *    standard glob syntax (wildcards, globstars, braces, extglobs, character
 *    classes) using Vitest with mocked directory handles, stress-testing
 *    performance for large brace expansions through regex-based segment
 *    matching, and verifying the reliability of options such as maxDepth,
 *    ignore, and AbortSignal cancellation.
 *  Generated on: 2026-03-31
 * ============================================================================
 */
/**
 * テスト用フィクスチャの自動生成・削除を行うモジュールじゃ。
 * `beforeAll` で `createFixtures()` を呼び、`afterAll` で `removeFixtures()` を呼ぶのじゃぞ。
 *
 * 生成先は OS の一時ディレクトリ配下 (`os.tmpdir()/glob-web-fs-fixtures`) じゃ。
 */
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

export const FIXTURE_ROOT = path.join(
  os.tmpdir(),
  `glob-web-fs-fixtures-${process.env.VITEST_WORKER_ID || Math.random().toString().slice(2, 8)}`,
)

// ────────────────────────────────────────
// ファイル一覧の生成ロジック
// ────────────────────────────────────────

function buildFileList(): string[] {
  const files: string[] = []

  // ヘルパー: 配列の直積を返す
  const cross = (a: string[], b: string[]) => a.flatMap((x) => b.map((y) => x + y))

  // ヘルパー: prefix/name の形式でまとめて追加
  const add = (dir: string, names: string[]) =>
    names.forEach((n) => files.push(`${dir}/${n}`))

  // ========================================
  //  1. ルート直下（約15）
  //     * の基本検証、拡張子バリエーション
  // ========================================
  add('', [
    'a.txt',
    'b.txt',
    'c.js',
    'd.ts',
    'e.tsx',
    'f.css',
    'g.json',
    'h.md',
    'i.html',
    'readme.txt',
    'LICENSE',
    'Makefile',
    'package.json',
    'tsconfig.json',
    'vite.config.ts',
  ])

  // ========================================
  //  2. basic/ — ワイルドカード `*` `?` 検証（約40）
  //     ファイル名の長さ・拡張子のバリエーション
  // ========================================
  {
    const dir = 'basic'
    // 1文字〜5文字 × 複数拡張子（? の桁数テスト）
    const names = ['a', 'b', 'c', 'x', 'y', 'z']
    const exts = ['.txt', '.js', '.ts']
    add(dir, cross(names, exts))

    const twoChar = ['ab', 'cd', 'xy']
    add(dir, cross(twoChar, exts))

    const threeChar = ['abc', 'def', 'xyz']
    add(dir, cross(threeChar, exts))

    const fourFive = ['abcd', 'test', 'hello']
    add(dir, cross(fourFive, ['.ts', '.tsx']))

    // サブディレクトリ
    add(`${dir}/sub`, ['foo.ts', 'bar.js', 'baz.txt'])
    add(`${dir}/sub/nested`, ['deep.ts', 'deep.js'])
  }

  // ========================================
  //  3. classes/ — 文字クラス `[abc]` `[a-z]` `[^...]` `[!...]` 検証（約80）
  //     a〜z, A〜Z, 0〜9 始まりのファイルを用意
  // ========================================
  {
    const dir = 'classes'
    // 小文字 a-z（26個）
    for (let i = 0; i < 26; i++) {
      const ch = String.fromCharCode(97 + i) // a-z
      files.push(`${dir}/${ch}.txt`)
    }
    // 大文字 A-Z（26個）
    for (let i = 0; i < 26; i++) {
      const ch = String.fromCharCode(65 + i) // A-Z
      files.push(`${dir}/${ch}.txt`)
    }
    // 数字 0-9（10個）
    for (let i = 0; i <= 9; i++) {
      files.push(`${dir}/${i}.txt`)
    }
    // アンダースコア・ハイフン始まり
    add(dir, ['_under.txt', '-dash.txt'])
    // 複合名（文字クラス + ワイルドカード併用テスト用）
    add(dir, [
      'apple.js',
      'banana.js',
      'cherry.ts',
      'Alpha.ts',
      'Beta.tsx',
      'Gamma.css',
    ])
    // サブディレクトリ
    add(`${dir}/sub`, ['a1.txt', 'B2.js', 'z9.ts'])
  }

  // ========================================
  //  4. posix/ — POSIX文字クラス `[[:alpha:]]` `[[:digit:]]` 検証（約30）
  // ========================================
  {
    const dir = 'posix'
    // 英字のみの名前
    add(dir, ['abc.txt', 'XYZ.txt', 'Hello.txt', 'WORLD.js'])
    // 数字のみの名前
    add(dir, ['123.txt', '456.js', '789.ts', '000.json'])
    // 英数字混合
    add(dir, ['a1b2.txt', 'X9Y8.js', 'test123.ts'])
    // 記号混じり（alpha/digit に「マッチしない」ことの検証用）
    add(dir, ['_test.txt', '-file.js'])
    // サブディレクトリ
    add(`${dir}/alpha`, ['aaa.txt', 'BBB.js', 'cCc.ts'])
    add(`${dir}/digit`, ['111.txt', '222.js', '333.ts'])
    add(`${dir}/mixed`, ['a1.txt', 'B2.js', '3c.ts', 'D4e.tsx'])
  }

  // ========================================
  //  5. extglobs/ — 拡張グロブ !() ?() +() *() @() 検証（約50）
  //     パターンの対象となる名前のバリエーション
  // ========================================
  {
    const dir = 'extglobs'
    // @(foo|bar) 検証用
    add(dir, ['foo.ts', 'bar.ts', 'baz.ts', 'qux.ts', 'quux.ts'])
    // !(baz) 検証用（baz 以外にマッチするべきもの）
    add(dir, ['foo.js', 'bar.js', 'baz.js', 'qux.js'])
    // ?(prefix) 検証用（prefix があってもなくてもよい）
    add(dir, [
      'test.txt',
      'pretest.txt',
      'prepretest.txt',
      'file.txt',
      'prefile.txt',
    ])
    // +(ab) 検証用（ab の1回以上繰り返し）
    add(dir, ['ab.ts', 'abab.ts', 'ababab.ts', 'abc.ts', 'ba.ts'])
    // *(xy) 検証用（xy の0回以上繰り返し）
    add(dir, ['xy.js', 'xyxy.js', 'xyxyxy.js', 'x.js', 'y.js'])
    // サブディレクトリの拡張グロブ
    add(`${dir}/nested`, [
      'foo.ts',
      'bar.ts',
      'baz.ts',
      'foo.test.ts',
      'bar.test.ts',
      'baz.test.ts',
    ])
    // .test.ts パターン（拡張子の複合検証）
    add(dir, [
      'app.test.ts',
      'app.spec.ts',
      'app.test.js',
      'app.spec.js',
      'util.test.ts',
      'util.spec.ts',
    ])
  }

  // ========================================
  //  6. symbols/ — 特殊記号を含むファイル名（約25）
  //     Windows で作成可能な記号のみ使用
  //     エスケープのテストに使うのじゃ
  // ========================================
  {
    const dir = 'symbols'
    add(dir, [
      '[test].txt', // 角括弧
      '[abc].js', // 角括弧
      '[!neg].ts', // 角括弧 + !
      '(parens).txt', // 丸括弧
      '{braces}.js', // 中括弧
      '{a,b}.ts', // 中括弧 + カンマ
      '!(negext).txt', // 拡張グロブ風の名前
      '@(at).js', // 拡張グロブ風の名前
      '+(plus).ts', // 拡張グロブ風の名前
      '#hash.txt', // ハッシュ
      '$dollar.js', // ドル記号
      '%percent.ts', // パーセント
      '&ampersand.txt', // アンパサンド
      '=equals.js', // イコール
      'my file.txt', // 空白
      'multi  space.js', // 連続空白
    ])
    // マルチバイト文字
    add(dir, ['日本語.txt', 'テスト.js', 'ファイル.ts', '한국어.txt', '中文.js'])
    // サブの記号ディレクトリ
    add(`${dir}/[bracketed]`, ['inside.txt', 'file.js'])
    add(`${dir}/{curly}`, ['inside.txt', 'file.ts'])
  }

  // ========================================
  //  7. dotfiles/ — ドットファイル・隠しディレクトリ（約40）
  //     dot オプション検証用
  // ========================================
  {
    const dir = 'dotfiles'
    // ルートレベルの隠しファイル
    add(dir, [
      '.env',
      '.gitignore',
      '.eslintrc.js',
      '.prettierrc',
      '.editorconfig',
      '.npmrc',
      'visible.txt',
      'normal.js',
    ])
    // 隠しディレクトリ
    add(`${dir}/.hidden`, ['secret.txt', 'config.json', 'data.js'])
    add(`${dir}/.hidden/deep`, ['nested.txt', 'nested.js'])
    add(`${dir}/.vscode`, ['settings.json', 'extensions.json'])
    add(`${dir}/.github`, ['config.yml'])
    add(`${dir}/.github/workflows`, ['ci.yml', 'deploy.yml'])
    // 隠しファイルと通常ファイルが混在するディレクトリ
    add(`${dir}/mixed`, [
      '.secret',
      '.hidden.txt',
      'public.txt',
      'normal.js',
      '.deep.config.json',
    ])
    add(`${dir}/mixed/sub`, ['.a', '.b', 'c.txt', 'd.js'])
    // ドットで始まる拡張子（.env.local など）
    add(dir, ['.env.local', '.env.production', '.env.test'])
  }

  // ========================================
  //  8. deep/ — 深いネスト検証用（約60）
  //     maxDepth と ** の限界テスト
  // ========================================
  {
    // 各階層にファイルを配置（depth 1〜15）
    let currentPath = 'deep'
    for (let depth = 1; depth <= 15; depth++) {
      currentPath += `/d${depth}`
      files.push(`${currentPath}/file.txt`)
      files.push(`${currentPath}/data.js`)
      // 偶数階層には追加ファイル
      if (depth % 2 === 0) {
        files.push(`${currentPath}/extra.ts`)
        files.push(`${currentPath}/bonus.json`)
      }
    }
    // 別のブランチ（幅方向の走査テスト）
    add('deep/branch-a', ['file.txt', 'data.js'])
    add('deep/branch-b', ['file.txt', 'data.ts'])
    add('deep/branch-a/child', ['nested.txt'])
    add('deep/branch-b/child', ['nested.txt'])
    add('deep/branch-a/child/grandchild', ['bottom.txt'])
  }

  // ========================================
  //  9. dirs/ — 空ディレクトリ検証用
  //     nodir オプション・末尾スラッシュ検証
  //     （ディレクトリのみで files には入れぬ。別途 emptyDirs で定義）
  // ========================================

  // ========================================
  // 10. massive/ — 大量ファイル検証用（500個）
  //     ブレース展開の限界・パフォーマンステスト
  // ========================================
  {
    const dir = 'massive'
    for (let i = 1; i <= 500; i++) {
      const ext =
        i % 3 === 0 ? '.ts'
        : i % 3 === 1 ? '.txt'
        : '.js'
      files.push(`${dir}/file_${i}${ext}`)
    }
    // サブディレクトリにも少し
    for (let i = 1; i <= 50; i++) {
      files.push(`${dir}/sub/item_${i}.txt`)
    }
  }

  // ========================================
  // 11. multi/ — 複数階層に同名ファイルが散らばるケース（約40）
  //     globstar + 完全一致のエッジケース検証
  // ========================================
  {
    const dirs = [
      'multi',
      'multi/a',
      'multi/b',
      'multi/a/x',
      'multi/b/x',
      'multi/a/x/y',
      'multi/b/x/y',
    ]
    for (const d of dirs) {
      add(d, ['index.ts', 'utils.ts', 'types.ts'])
    }
    // 特定ディレクトリだけ追加ファイル
    add('multi/a', ['only-a.ts'])
    add('multi/b', ['only-b.ts'])
    add('multi/a/x', ['only-ax.ts'])
  }

  // ========================================
  // 12. ignore/ — ignore オプション検証用（約50）
  //     除外パターンの複雑なケースをテスト
  // ========================================
  {
    const dir = 'ignore'
    add(dir, ['keep.ts', 'remove.ts', 'keep.js', 'remove.js'])
    add(`${dir}/src`, ['app.ts', 'app.test.ts', 'app.spec.ts'])
    add(`${dir}/src/utils`, ['helper.ts', 'helper.test.ts', 'format.ts'])
    add(`${dir}/src/components`, ['Button.tsx', 'Input.tsx', 'Modal.tsx'])
    add(`${dir}/src/services`, ['api.ts', 'auth.ts', 'api.test.ts'])
    add(`${dir}/dist`, ['bundle.js', 'bundle.min.js', 'bundle.css'])
    add(`${dir}/node_modules/pkg`, ['index.js', 'package.json'])
    add(`${dir}/__tests__`, ['app.test.ts', 'utils.test.ts'])
    // 深い階層の除外テスト
    add(`${dir}/src/deep/nested/path`, ['file.ts', 'file.test.ts'])
  }

  // ========================================
  // 13. trailing/ — 末尾スラッシュ検証用（約30）
  //     ディレクトリのみマッチのテスト
  // ========================================
  {
    const dir = 'trailing'
    // ディレクトリ内にファイルを1つずつ配置（ディレクトリの存在を保証）
    const subDirs = [
      'alpha',
      'beta',
      'gamma',
      'alpha/one',
      'alpha/two',
      'beta/three',
      'gamma/four/five',
    ]
    for (const sub of subDirs) {
      add(`${dir}/${sub}`, ['marker.txt'])
    }
    // ルート直下のファイル（ディレクトリではないので末尾/にマッチしてはならぬ）
    add(dir, ['file1.txt', 'file2.js', 'file3.ts'])
  }

  // ========================================
  // 14. braces/ — ブレース展開 `{a,b}` `{1..5}` 検証用（約30）
  // ========================================
  {
    const dir = 'braces'
    add(dir, [
      'foo.ts',
      'bar.ts',
      'baz.ts',
      'qux.ts',
      'foo.js',
      'bar.js',
      'baz.js',
      'qux.js',
      'foo.css',
      'bar.css',
    ])
    add(`${dir}/a`, ['file.ts', 'file.js'])
    add(`${dir}/b`, ['file.ts', 'file.js'])
    add(`${dir}/c`, ['file.ts', 'file.js'])
    // 数値レンジ展開のテスト用
    for (let i = 1; i <= 10; i++) {
      files.push(`${dir}/item${i}.txt`)
    }
  }

  return files
}

/**
 * ファイルを持たぬ空ディレクトリの一覧じゃ。
 * nodir オプションや末尾スラッシュの検証で「中身が空のディレクトリ」が必要じゃからの。
 */
function buildEmptyDirs(): string[] {
  return [
    'dirs/empty1',
    'dirs/empty2',
    'dirs/empty3',
    'dirs/parent/empty-child',
    'dirs/parent/another-empty',
    'dirs/nested/deep/empty',
    'trailing/empty-dir',
  ]
}

// ────────────────────────────────────────
// 作成・削除
// ────────────────────────────────────────

/**
 * テスト用フィクスチャを一括生成するのじゃ。
 * 既にディレクトリが存在する場合は一旦消してからやり直すぞ。
 */
export function createFixtures(): void {
  // 既存があれば削除してクリーンな状態にする
  removeFixtures()

  const fileList = buildFileList()
  const emptyDirs = buildEmptyDirs()

  // ファイル作成（親ディレクトリも再帰的に作る）
  for (const relPath of fileList) {
    const absPath = path.join(FIXTURE_ROOT, relPath)
    fs.mkdirSync(path.dirname(absPath), { recursive: true })
    fs.writeFileSync(absPath, '') // 空ファイル
  }

  // 空ディレクトリの作成
  for (const relDir of emptyDirs) {
    fs.mkdirSync(path.join(FIXTURE_ROOT, relDir), { recursive: true })
  }

  const totalFiles = fileList.length
  const totalDirs = new Set([...fileList.map((f) => path.dirname(f)), ...emptyDirs])
    .size
}

/**
 * テスト用フィクスチャを丸ごと削除するのじゃ。
 */
export function removeFixtures(): void {
  if (fs.existsSync(FIXTURE_ROOT)) {
    fs.rmSync(FIXTURE_ROOT, { recursive: true, force: true })
  }
}

/*!
 * ============================================================================
 *                                AI Generation End
 * ============================================================================
 */
